name: test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  PYTHONPATH: src
  PIP_ROOT_USER_ACTION: ignore

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: lint
        run: |
          black --check src tests
          ruff check --format=github src tests
          mypy --install-types --non-interactive

      - name: Test with pytest
        run: pytest
